version: '1.0'

services:

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shortener
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306

  myapp-main:
    build:
      context: .
      dockerfile: Dockerfile
    image: learn/url-shortener
    depends_on:
      - db
    ports:
      - 8080:8080